### ISSUE TITLE
关于jd_cfd_loop.ts脚本的优化

### ISSUE THREAD

**Issue by wxjbb** [JDHelloWorld/jd_scripts#102]
jd_cfd_loop.ts脚本会一直在后台运行，如果cookie失效了，即使更新了cookie，之前跑的进程还是一直在使用旧cookie，导致疯狂收到cookie失效的通知。
这里能否进行优化呢，比如每次循环执行时重新读取环境变量

**Comment by 8183736** [comment]
优化个锤子，自己重启下服务不就行了

**Comment by JDHelloWorld** [comment]
自己不会去重启进程？
