### ISSUE TITLE
大佬可以考虑增加个关闭“上报失败！”的变量控制吗？

### ISSUE THREAD

**Issue by xsj684135** [JDHelloWorld/jd_scripts#103]
相信有大部分人是没有加群的 好像都使用不了这个功能 但是总是推送 今天把我pushplus的200条额度用完啦，所以请大佬考虑下加个变量来控制是否推送“上报失败！”

**Comment by Kylin2021** [comment]
+1

**Comment by xsj684135** [comment]
想加群也加不了群 都找不到群在哪 o(╥﹏╥)o

**Comment by JDHelloWorld** [comment]
现在是始终返回成功，如果报失败，就是连接api出错

**Comment by hello1983** [comment]
可以加我 进群吗 @Q_tang 谢谢
