### ISSUE TITLE
jd_live_redrain报错

### ISSUE THREAD

**Issue by enews** [JDHelloWorld/jd_scripts#11]
![1234](https://user-images.githubusercontent.com/9135007/122055495-4448e980-ce1b-11eb-957f-454db611684a.png)
从cdn里面获取id时报错了，我把提示信息格式化了下，报错内容是“Request path contains unescaped characters”，
![223](https://user-images.githubusercontent.com/9135007/122056742-7f97e800-ce1c-11eb-97fa-a1e6f11f3cc7.png)

大佬能不能在请求时encodeURI一下

**Comment by lksky8** [comment]
这个活动好像已经没了吧
