### ISSUE TITLE
关于 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module 错误

### ISSUE THREAD

**Issue by singyueyang** [JDHelloWorld/jd_scripts#114]
![image](https://user-images.githubusercontent.com/65761345/126874373-cc76fb2d-afe0-443b-99b8-2be5544b8e53.png)

我在一台新机器上安装了青龙面板，然后拉取仓库之后，全部脚本都提示这个错误，我安装了一些依赖，比如： png-js date-fns got等，还是照样错误，我上网搜索这个错误，说是node的版本太高了，得降级才行（我未升级过NODE的版本，就是默认的V14.17.3），于是我使用n 命令安装指定版本，但是国外镜像太慢太慢，导致无法安装，

请问各位大神：
1、这种报错该怎么排除呢？
2、n命令如何加快下载速度？是否可以切换国内源？

**Comment by LevineWoo** [comment]
@singyueyang 看网上说是你的nodejs版本太高，要不降级，要不等作者更新语法

**Comment by singyueyang** [comment]
> @singyueyang 看网上说是你的nodejs版本太高，要不降级，要不等作者更新语法

那就是说，这几天就没豆子可收了  -_- ...

**Comment by singyueyang** [comment]
**结贴**。终于知道原因了，是新机器青龙面板DOCKER都没安装完成，我就点了重启导致的，后面我重装一次就正确了，**总结：手贱~~~**
