### ISSUE TITLE
 Cannot find module '../TS_USER_AGENTS' or its corresponding type declarations

### ISSUE THREAD

**Issue by jim114042** [JDHelloWorld/jd_scripts#119]
Cannot find module '../TS_USER_AGENTS' or its corresponding type declarations

这个怎么解决？是缺少文件夹吗

**Comment by slj844909754** [comment]
同问

**Comment by jim114042** [comment]
解决了 我把../TS_USER_AGENTS 改成 ./TS_USER_AGENTS就OK了
