### ISSUE TITLE
财富岛，明明建过房子了，还提示手动建房子

### ISSUE THREAD

**Issue by AboutCXJ** [JDHelloWorld/jd_scripts#128]
<img width="243" alt="截屏2021-08-03 22 26 37" src="https://user-images.githubusercontent.com/19811825/128033170-2edf7289-c1db-4e7b-a92d-50bf9b08ca4a.png">
![WechatIMG1622](https://user-images.githubusercontent.com/19811825/128033188-f53f0876-745e-4479-8428-a7e56a9bf011.jpeg)

**Comment by Aerozb** [comment]
我也是

**Comment by JDHelloWorld** [comment]
500
