### ISSUE TITLE
getJDCookie.js无法正常使用

### ISSUE THREAD

**Issue by ITdesk01** [JDHelloWorld/jd_scripts#13]
node getJDCookie.js
![image](https://user-images.githubusercontent.com/38835844/122371536-87799880-cf92-11eb-9e3b-9b8e330c4d48.png)

其他异常：{"check_ip":0,"errcode":258,"message":"服务异常，请稍后重试"}

差不多十来秒左右就会出现这个问题，请大佬修复这个问题

**Comment by JDHelloWorld** [comment]
JD问题，刚试了又不报错了，脚本不用修。

**Comment by google-mirror** [comment]
不行, 还没扫码就提示

您的账号存在风险，请您稍后再试或联系客服
