### ISSUE TITLE
无法获取京豆 jd_bean_change.js

### ISSUE THREAD

**Issue by xsj684135** [JDHelloWorld/jd_scripts#130]
除京豆外 其他正常，不知是否为个例
今日收入：0京豆 🐶
昨日收入：0京豆 🐶
昨日支出：0京豆 🐶

**Comment by id77** [comment]
@xsj684135 有个API请求太频繁了，被限制了。

**Comment by xsj684135** [comment]
> @xsj684135 有个API请求太频繁了，被限制了。

jd已经开始这样了...

**Comment by id77** [comment]
@xsj684135 有部分api一直以来都有这种限制。你自己用的脚本存在滥用api；或者你设置的任务频率太高
