### ISSUE TITLE
enen.js 无法执行下去

### ISSUE THREAD

**Issue by Wake2020** [JDHelloWorld/jd_scripts#136]
🔔嗯嗯, 开始!

====================共14个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021-8-25 11:53:48 AM=====================

一直卡在这里不懂，请问是怎么回事？

**Comment by Wake2020** [comment]
有ck外泄了，想用此脚本失效ck，为啥在面板里主动执行没有反应呢？

**Comment by JDHelloWorld** [comment]
删除代码里2个continue
