### ISSUE TITLE
关于助力池访问的问题

### ISSUE THREAD

**Issue by yogayyy** [JDHelloWorld/jd_scripts#139]
大佬，阿里云是不是访问助力池有问题？我每天都会跑n次，但还是被清了，按理说访问失败一两次有可能，所有活动全天访问助力池都失败就不能理解了，之前腾讯云是ok的。这个有办法解决吗，打扰啦🌝

getaddrinfo EAI_AGAIN api.sharecode.ga

**Comment by Jone2008** [comment]
你把这个api地址，强制走代理试试

**Comment by yogayyy** [comment]
收到，我试试
