### ISSUE TITLE
jd_reward.js无法调用TS_USER_AGENTS.ts

### ISSUE THREAD

**Issue by OCD0711** [JDHelloWorld/jd_scripts#164]
是不是放错脚本了 jd_reward 应该也是 ts 脚本吧, 即使 TS_USER_AGENTS.ts 转 js 之后 jd_reward 调用无法获取到cookie

**Comment by JDHelloWorld** [comment]
process.argv[2]

**Comment by OCD0711** [comment]
> process.argv[2]

修好了 thx
