### ISSUE TITLE
京喜牧场疯狂通知“牧场卡片可兑换”

### ISSUE THREAD

**Issue by yunv7** [JDHelloWorld/jd_scripts#174]
京喜牧场疯狂通知“牧场卡片可兑换”，然而进去兑换的时候小鸡已经满了，不让兑换，然后每运行一次就会通知一次。。可否在牧场鸡满的情况下不提示呢

**Comment by JDHelloWorld** [comment]
你从哪行代码看见有通知了？

**Comment by yunv7** [comment]
![image](https://user-images.githubusercontent.com/85724850/141717262-dbf389cb-14f7-4b60-8837-984891775bd9.png)

如图，jxmc.ts 116行这个
> 你从哪行代码看见有通知了？

**Comment by yunv7** [comment]
我的问题，自动更新出问题了，提示了个The following untracked working tree files would be overwritten by merge:jd_cfd_hb.js
删了才更新成功，没这提示了

**Comment by JDHelloWorld** [comment]
![QQ20211115-113204](https://user-images.githubusercontent.com/77717629/141718182-b2fa55a2-79f2-40cc-9525-ef9ae40ad694.png)
