### ISSUE TITLE
惊喜牧场好友助力bug了提示全部助力成功，实际并未助力。

### ISSUE THREAD

**Issue by aTenb** [JDHelloWorld/jd_scripts#177]
获取到30个随机助力码: [
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDj5-roiTdcW28UDmEtm9jJQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbK3HeHmT7vvTidYDeC4GNl1yLA-Z1yhYLBrN9NtFG7AA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZCoqbS0ss3tESKVCxlMjEXb9KeLOHqy8tXP02XhRrwtg',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbPg1cjnXyEDPDTMmtJqgtOtj4CR8Jy5tPUrOBEsJYNLg',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZNmfGBM_teRK6x38KpeV7kob7RAOhzQM5C2k27sCc1KA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDKoC-DIoYI34lmWGk87j57g',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZE68s7MEON9JG1p6-5Q-ZSilAaXNcxsFls4cEKf334VQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZb-76B4KALhsP3aylG0cFYBj4WcTeWvbdTD1HB2hr1gA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDDVzherU_UQbQU6yZ3z3KnQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZww5wuyEaMRbaL5mAsTnsGbkDTrusP8LzZpvDCHRV10A',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKD_8vSAA3_QTnKlplka-xliQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDY3DJru-EqoNRLklnxK1uOw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZE68s7MEON9JG1p6-5Q-ZSRVkgQdEDA_ZTMLyOxSl4Pw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZ5yr2QGQmgEt7evbpkz7Qgd8bHdSEkiGFa3sQ8HKpArw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbIYRsAVWql012UuI9xzC79EJv11K3Di2fRAV2srkCiGw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYEP-GHw9_TA7I3WswtPjV2J2xIKbsZW1TF7mB-KMCQbQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHca5WhiXJzzggfYP-aYWU1lW70l6iG-iou7ZOEDrxFwh9w',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZaektpT7PJobUgewnxqoIZKXJJEVGPjcg07B7Y1OFNZA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbNvzD_epKy52ApmrilBbbEzONtujD3PgDwaKkuiFUMKA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbjk0Su43ZpjJca6GCUboWY0bCZkmHITpz03UALnx0KWQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYUvFE-h5V5taoDarTpzPAjDhBjhtRelDsLQCrLhgSKAA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYh9zI8fohVg8TXTcxpEdlMPrRARoM1HkODm6ZxaFf-mQ',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYjs7R4IOpf5Bg5_Y7X7JLu1PKS17eS20AmhHtY463e9A',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcatPvLTG6eWT-iXSXK1WohbdNH5raIIVK1Cm7kbhrdJ1g',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYyQsTCAhd9wHcTNr4lNtFvftAXo2iJXrw8QFSNziZ23w',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZE68s7MEON9JG1p6-5Q-ZSpYx9IwwSLXDWqtfiIwExXw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZtRMl3P71in5wNpX5_phoZ8Eo-l67ughlY44PYt6fJvw',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbtHK-LR1Msz2LD3AplrE9O0_WTE1aBnyVGOk5lk51G2Q',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcaEax1huXAzkmhccVjM-cqYRQdhQKJP1i-bphczAaMdJA',
  'g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbx0DiQxWPjqY3NYuArnAgxu1FYoWSATvPTm_NQokSJMQ'
]
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbkQpoTYBFd_ZwPevsFs76e9sBhJ0Cv4abwkqpAFqr3JA
成功，获得: undefined
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHca0EqEpPSfYVm8sF28-tAcrCeixv3qL1xIvkEP0erxFKQ
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcaob4TlUNryAToVK5MWI-k7CP0iHype8T7pfkID4b2yhw
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbx0DiQxWPjqY3NYuArnAgxJz-kdmqAQq0Lc2YE27G_fw
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDj5-roiTdcW28UDmEtm9jJQ
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbK3HeHmT7vvTidYDeC4GNl1yLA-Z1yhYLBrN9NtFG7AA
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZCoqbS0ss3tESKVCxlMjEXb9KeLOHqy8tXP02XhRrwtg
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcbPg1cjnXyEDPDTMmtJqgtOtj4CR8Jy5tPUrOBEsJYNLg
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZNmfGBM_teRK6x38KpeV7kob7RAOhzQM5C2k27sCc1KA
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDKoC-DIoYI34lmWGk87j57g
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZE68s7MEON9JG1p6-5Q-ZSilAaXNcxsFls4cEKf334VQ
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZb-76B4KALhsP3aylG0cFYBj4WcTeWvbdTD1HB2hr1gA
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDDVzherU_UQbQU6yZ3z3KnQ
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZww5wuyEaMRbaL5mAsTnsGbkDTrusP8LzZpvDCHRV10A
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKD_8vSAA3_QTnKlplka-xliQ
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcYVVRMyG1St4rxb62oZ4jKDY3DJru-EqoNRLklnxK1uOw
成功，获得: 0
账号1去助力g_eiitD1h9-a-PX-GytKiGrfw77E3iG0LpMlIb2JHcZE68s7MEON9JG1p6-5Q-ZSRVkgQdEDA_ZTMLyOxSl4Pw

**Comment by aTenb** [comment]
显然一个号是不可能全部助力成功的。实际没成功，又不能退出循环。

怀疑是京东接口已经变了。

还有惊喜牧场，红包助力也有一个bug。如果火爆的话，也不能退出循环。

**Comment by aTenb** [comment]
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkqjoA2698EJMH_UVRAPmi8O0-TBD1sZYv03l6Xp3s3-3FdrlcmOfqUssx3tQWTgaRh
失败： { data: {}, message: '活动太火爆啦，先去逛逛好物吧', ret: 1016 }
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkq-orIBvMgW-XmYHR192eU9C9J7eg58BD71JP3ujcZa9iZ_xV58rzh6gIQyHU7kjln
失败： { data: {}, message: '活动太火爆啦，先去逛逛好物吧', ret: 1016 }
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkqbn7uWiq6yBtJXSTgjvAzrO0UzWk5v6KEcC7AWmbJt5ygBW7Hx2g2-bZwn9StJaxJ
失败： { data: {}, message: '活动太火爆啦，先去逛逛好物吧', ret: 1016 }
账号4去助力undefined
失败： { data: {}, message: '系统君失联，请刷新重试~', ret: 1000 }
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkqaN5HxYdq8Ds-io4ORkZbiVnhSljL8sCwamjwQBNfd0o
失败： { data: {}, message: '活动太火爆啦，先去逛逛好物吧', ret: 1016 }
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkqpHua7jaAt-HZD11K068JlgdbUgeduz_qVXFMjglZemMCdK44R-qdhbYF6-hLeY2d
失败： { data: {}, message: '活动太火爆啦，先去逛逛好物吧', ret: 1016 }
账号4去助力g_eiitD1h9-a-PX-GytKiCP4Y59In6jxprR7viqVfh9G6Y6I8tyY2Llff4vPuGkqEY75

**Comment by aTenb** [comment]
惊喜牧场，红包助力会出现ret1016得情况。黑号不能退出助力，及时excpet去掉了黑号cookies还是会参与助力，并导致bug不能退出循环

**Comment by JDHelloWorld** [comment]
成功，获得: 0。自己没次数或者别人满了
火爆的自己号有问题

有问题的没有break
助力时确实没有读取exceptCookie
