### ISSUE TITLE
报告一些过期、运行错误的脚本

### ISSUE THREAD

**Issue by DarkAge2018** [JDHelloWorld/jd_scripts#179]
- jd_kd.js 提示异常 非法请求
- jd_jxnc.js 入口已经找不到了，之前已经无法领种子，应该是正式下线了
- jd_IndustryLottery.ts **Cannot read properties of null (reading 'taskConfig')**
- jd_qq_pasture.ts ** Cannot read properties of undefined (reading '1')**
- jd_nzmh.js **Cannot read properties of undefined (reading 'bless')**

**Comment by JDHelloWorld** [comment]
有几个没有移除的自己删下定时吧，有人要跑
