### ISSUE TITLE
TG群怎么了，怎么变私人了？

### ISSUE THREAD

**Issue by DengYunJun** [JDHelloWorld/jd_scripts#181]
还是我被拉黑了？

**Comment by dmcslt** [comment]
白嫖你被踢了

**Comment by JDHelloWorld** [comment]
Bingo!

**Comment by DengYunJun** [comment]
![image](https://user-images.githubusercontent.com/47079069/143679968-daf03862-107c-4be7-8ca2-f4270e2d0741.png)这也算白嫖吗？

**Comment by dmcslt** [comment]
你有码子在黑名单

**Comment by DengYunJun** [comment]
> 你有码子在黑名单

好吧，那就不知道了，感谢解答

**Comment by dmcslt** [comment]
假设你5个号，你农场5个正常助力，但你汪汪工厂等其他任何码子被判断白嫖了，那你就会被t

**Comment by MyGhost233** [comment]
同样被T了不知道是不是惊喜工厂经常没东西生产的原因。。。。。
