### ISSUE TITLE
jd_order_cashback.ts上传失效了

### ISSUE THREAD

**Issue by EchoChan314** [JDHelloWorld/jd_scripts#189]
Error: Request failed with status code 500
    at createError (/usr/local/pnpm-global/5/node_modules/.pnpm/axios@0.24.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/pnpm-global/5/node_modules/.pnpm/axios@0.24.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/pnpm-global/5/node_modules/.pnpm/axios@0.24.0/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.24.0'
    },
    method: 'get',
    url: 'https://api.jdsharecode.xyz/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.jdsharecode.xyz',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.jdsharecode.xyz',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 88,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3 HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.24.0\r\n' +
      'Host: api.jdsharecode.xyz\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'INTERNAL SERVER ERROR',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.jdsharecode.xyz/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.jdsharecode.xyz',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.jdsharecode.xyz/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'INTERNAL SERVER ERROR',
    headers: {
      server: 'nginx',
      date: 'Thu, 16 Dec 2021 06:52:45 GMT',
      'content-type': 'text/html; charset=utf-8',
      'content-length': '290',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'get',
      url: 'https://api.jdsharecode.xyz/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'Host: api.jdsharecode.xyz\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/autoInsert/fanxian?sharecode=2a17d6ebc81cf0dd05b1a04008b1edee&bean=3ifix6gkqqjzjktjhfotip4s52uheugtzu4kzmi&farm=3a191340d4aa43c3af3a1f618ee86c10&pin=b6093950d9c29f4df2bc47d4e92452e3',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.jdsharecode.xyz',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n' +
      '<title>500 Internal Server Error</title>\n' +
      '<h1>Internal Server Error</h1>\n' +
      '<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by JDHelloWorld** [comment]
.

**Comment by EchoChan314** [comment]
> .

请问是啥问题呀
