### ISSUE TITLE
电竞经理脚本多账号自动助力失败

### ISSUE THREAD

**Issue by hdstar2009** [JDHelloWorld/jd_scripts#20]
内部助力没成功1个。

**Comment by hdstar2009** [comment]
看了日志，原来所有的账号等是生成同一个助力码了，因此没助力成功吧

【京东账号1（_m）的东东电竞经理好友互助码】YnKZNR1AYeo=

isvToken:AAEAILu8qB9nSxiBGNGK5wy7J-WchpZmW5i_T52YhuV9yRCq0
token2:AAFgz_eVADCjMjzeySwltcSrOP5WaHQXBpEnyUG3xuvqVCuV2ssiB30ksVV0fdeLzp4xpfhN3ok
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjRHF1SWFFbVlTZS1qQXNvQm90cEtaWkxnUkc1Z1dFejJwdms2N05zcU5RIiwiaXNzIjoiY29tLnNpbnJld2ViIiwiZXhwIjoxNjI0ODQ2ODcwLCJpYXQiOjE2MjQyNDIwNzB9._bmGxVq3z-WqeXBDy5CCDIuKKMcrZFe0bAHRyGUOA_c
收币： { status: '0', message: 'ok', body: { coins: '10' } }
收币成功：获得 10
第1个账号630784_m去助力第1个账号。
1 shareCodes[0]

开始【京东账号2】


【京东账号2（ya）的东东电竞经理好友互助码】YnKZNR1AYeo=

isvToken:AAEAIL9lZQ_4tI8_B7in3yWaOWkeNc1pwZdgoXdi4SrQoym30
token2:AAFgz_ecADB9Oyo8jWtisYkTnXkbnVYwKCFaryIhTK77DCU1ybgeaGb9vDwJ4LK9AESQdKb1xP0
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJfeGJqSVBRTV85LXIxWnVZeDNneDlZNDJEVkdGdnAxVDlqVnVBbk9JdXJZIiwiaXNzIjoiY29tLnNpbnJld2ViIiwiZXhwIjoxNjI0ODQ2ODc2LCJpYXQiOjE2MjQyNDIwNzZ9.Zya_h6i8RzYmL9IXZ8lv7FjNcOdjIfSDMrjJnQPNb9w
收币： { status: '0', message: 'ok', body: { coins: '9' } }
收币成功：获得 9
第2个账号a去助力第1个账号。
2 shareCodes[0]

开始【京东账号3】017


【京东账号3（0c）的东东电竞经理好友互助码】YnKZNR1AYeo=

isvToken:AAEAIEO3ERYgzO6OO2g3-nfaG1k-wVOKFWtdtQMwXNMhE-Af0
token2:AAFgz_eiADBOz641CtJdEApQMtsBvOWvrSLSS8BTKH3_SMe4DuFvQEP0CJDZ_M2dQz2z9vB0beI
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJDSmtpbUUxcjF0NXdYS0lOLUE3VDVLWDdGUjAxbk1ocFZOcjltTTQzbEZjIiwiaXNzIjoiY29tLnNpbnJld2ViIiwiZXhwIjoxNjI0ODQ2ODgyLCJpYXQiOjE2MjQyNDIwODJ9.tDSUwkR4Lp242HCZ1GFt7CL6hSrMGRO9EqO7j9TFK6I
收币： { status: '0', message: 'ok', body: { coins: '9' } }
收币成功：获得 9
第3个账号0c去助力第1个账号。
3 shareCodes[0]

**Comment by JDHelloWorld** [comment]
fixed
