### ISSUE TITLE
jd_plantBean.js收取好友营养液无效

### ISSUE THREAD

**Issue by Ms213s** [JDHelloWorld/jd_scripts#201]

**Comment by JDHelloWorld** [comment]
偷取好友营养液成功
开始收取营养液
收取-收取好友-的营养液
收取营养液结果:{"code":"0","data":{"growth":"166","nutrients":"0","beanState":"4","beanImg":"https://m.360buyimg.com/babel/jfs/t1/116429/19/11902/498078/5f053c2aE9cc6b0cd/x.gif"}}
【上轮京豆】已领取
