### ISSUE TITLE
jd_fruit_help最新版报错，然后净给别人助力了

### ISSUE THREAD

**Issue by mengdie101** [JDHelloWorld/jd_scripts#210]
开始【京东账号1】*****

第1个账号获取的内部互助 [""]
⬆️ 检查是否获取到内部互助码，有问题及时停止运行，15秒后开始执行
助力码 1742f8ef6f3141c7a17c3ade6629ab87
上报失败，未提交
随机获取50个farm成功：["874cd04e892a47cba2c1170f6ed67412","4072f83f18f44bb0a3675c92a8654aa0","35f1d407ae93478d9a9abca02f442dee","6549ab4b5d2840d6bfb29fddfa2ebf5b","d6f5f706887542e5aadcece136a7125e","f558bf3226ac48528e04c03dc486552a","5292c73dbbb94644846fdea34f7be217","0819922476fd4ff38ea9aec8afa83983","e2e5e1be41dd42a3b5f1351f5ede6842","2b6ead24eafb44e49cae45e78c83f118","67d0784703e0481caaced67dfbce2141","e6df8a0f3e1148aead188f22fbc4ca3a","2ed662e7b0fa4c90ac6018a24415430d","cc00bfc3f83c428db1758d6d2b875a40","00d8df56de9447939a88e1345cb5b3e7","b735892ec85541edb72ab98788c800d7","5f6cb0f1644b4dc6a0d66209ad407d1c","198f7ddd6a184fc48a9485929aa814e5","83dc037d134d441e91d960a268d22e79","38a11c7a04bc47359a1aca0aeec07f3b","afb34306565040c5b36c36cd4bdd747d","b43c9ddcee574062970c6cdfac3693b4","6111dae120d942a9bb08b94d1ce19d66","c4faa1bf82ed407ea612f104b6312022","a5710aae110b443787dcd890dc36b64c","f12104f8617542b9b6f709980c9d4bc2","46c84bc92d13488d94dd855b67acfbc7","92eccc6bfe2c4ce8b415e76ab1cf04e1","9ca304509dd649cfa242916182fd7fb3","7a2b57cb98dc49d29a068fd21d1b2407","0ffe39ed741b4f519f4e44a33b39d542","487b13937e334cd4878c562973ecaa9e","1e610d9d48c144ea90b951ef83acda3d","a6bc6a92f85a4f1899e672f7bea30641","fdb860d8c098496da50153f22cc9d599","d65828045e1449a4b5d11642f102d995","36ae38ff36e2443d9894b94628970fc1","2b6f246a35ff420094e95caa2f13d435","0888f07debd14f04bbfbc27e2841b875","aa5b67f950aa4b1a9cd36ce0bdcc7cca","d63a8cac87434d80a29ec7bcaf34fbed","f059b150d383446eb20c160afe151d95","41ff3a6102e14f089674ba50a1dc619f","b8f1e983fd7240849236df407bcbf230","681bd6e6feee473cb6c71b6dd586e5b9","0c1a4d62ec334e6b8a9406e0007c8a06","5e524bd4072c4dbbb02202fc5e9549a8","c44e5cc6833946ff8afd012dff51f83d","9501a2aa13c34ccdb7e7382da68d8992","17a2ec62b7a348a8a7e0b97a396d51ca"]
账号 ***** 去助力  *内部*
(node:1255) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at /jd/scripts/jd_fruit_help.js:179:36
    at step (/jd/scripts/jd_fruit_help.js:41:23)
    at Object.next (/jd/scripts/jd_fruit_help.js:22:53)
    at fulfilled (/jd/scripts/jd_fruit_help.js:13:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1255) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JDHelloWorld** [comment]
内部助力码都没设置对
