### ISSUE TITLE
宠汪汪是否和系统配置有关？

### ISSUE THREAD

**Issue by hua12lao** [JDHelloWorld/jd_scripts#30]
![image](https://user-images.githubusercontent.com/37362807/123028048-5de8c300-d411-11eb-8ae7-e78bc66819e5.png)
感觉是不是html里引用的问题（个人猜测）

**Comment by hyyds** [comment]
给代码567行加入try catch 解决上面那个报错.
运行后接着另一个报错信息出现在代码341行。
通过console.log打印 rawData变量得出html文本302.
就是指请求没成功。放在本地跑是没问题的。得出这个接口京东禁用了非大陆地址ip请求。
解决办法： 外网服务器代理到内地服务器进行该接口的请求就好了。

**Comment by JDHelloWorld** [comment]
多谢大佬，已加入catch提示
