### ISSUE TITLE
通过console.log打印 rawData变量得出html文本302.

### ISSUE THREAD

**Issue by shenmadouyaowen** [JDHelloWorld/jd_scripts#34]
通过console.log打印 rawData变量得出html文本302.
就是指请求没成功。放在本地跑是没问题的。得出这个接口京东禁用了非大陆地址ip请求。
解决办法： 外网服务器代理到内地服务器进行该接口的请求就好了。

我通过wget 获取那个请求是可以的,但是脚本就不行,大佬能在研究看看是啥情况吗?

_Originally posted by @hyyds in https://github.com/JDHelloWorld/jd_scripts/issues/30#issuecomment-866789603_

**Comment by basten1899** [comment]
大陆ip 一样显示"生成验证码必须使用大陆IP"

**Comment by JDHelloWorld** [comment]
dns
