### ISSUE TITLE
点点券二代目	报错 前面都运行正常 有一个号是黑号火爆就开始报错了

### ISSUE THREAD

**Issue by Kylin2021** [JDHelloWorld/jd_scripts#36]
bubble: 300 1514581805
(node:3556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'biz_code' of undefined
    at main (/ql/scripts/JDHelloWorld_jd_scripts_jd_necklace_new.js:247:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /ql/scripts/JDHelloWorld_jd_scripts_jd_necklace_new.js:189:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
更新任务状态成功

**Comment by Kylin2021** [comment]
任务也没继续执行下去 终止了

**Comment by hyyds** [comment]
res.data?. biz_code result.signInfo?.todayCurrentSceneSignStatus

**Comment by JDHelloWorld** [comment]
fixed
