### ISSUE TITLE
扫描登录 显示二维码失效

### ISSUE THREAD

**Issue by qiaodgn** [JDHelloWorld/jd_scripts#38]
扫描登录 显示二维码失效 拿不到cookie了

**Comment by qiaodgn** [comment]
![image](https://user-images.githubusercontent.com/56430818/123353832-feb3bb80-d594-11eb-95af-4bba03e8a482.png)

**Comment by GaoShin** [comment]
我这边提示的是：
其他异常：{"check_ip":1,"errcode":264,"message":"出错了，请退出重试"}

**Comment by shanke0303** [comment]
目前只有同网络情况下才会成功，异网扫码就提示二维码失效

**Comment by piaoyun** [comment]
> 我这边提示的是：
> 其他异常：{"check_ip":1,"errcode":264,"message":"出错了，请退出重试"}

这个是同网络的报错。
check_ip:1  是同网络

checkip:0  是异地网络

**Comment by GaoShin** [comment]
> > 我这边提示的是：
> > 其他异常：{"check_ip":1,"errcode":264,"message":"出错了，请退出重试"}
> 
> 这个是同网络的报错。
> check_ip:1 是同网络
> 
> checkip:0 是异地网络

既然都是同网络了，照理说应该是没问题的呀，那这个应该要如何处理？

**Comment by ykn1106** [comment]
> > > 我这边提示的是：
> > > 其他异常：{"check_ip":1,"errcode":264,"message":"出错了，请退出重试"}
> > 
> > 
> > 这个是同网络的报错。
> > check_ip:1 是同网络
> > checkip:0 是异地网络
> 
> 既然都是同网络了，照理说应该是没问题的呀，那这个应该要如何处理？

同样问题，没有wifi路由器的要怎么搞？

**Comment by avsba001** [comment]
> > > > 我这边提示的是：
> > > > 其他异常：{"check_ip":1,"errcode":264,"message":"出错了，请退出重试"}
> > > 
> > > 
> > > 这个是同网络的报错。
> > > check_ip:1 是同网络
> > > checkip:0 是异地网络
> > 
> > 
> > 既然都是同网络了，照理说应该是没问题的呀，那这个应该要如何处理？
> 
> 同样问题，没有wifi路由器的要怎么搞？

利用vpn构成同网络
