### ISSUE TITLE
QL拉取库失败

### ISSUE THREAD

**Issue by cherrymars** [JDHelloWorld/jd_scripts#57]
用的这个命令ql repo https://github.com/JDHelloWorld/jd_scripts.git "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"
拉取失败

日志如下：

开始执行... 2021/6/29 下午8:16:36

--------------------------------------------------------------

开始更新仓库：/ql/repo/JDHelloWorld_jd_scripts

Fetching origin
HEAD is now at 03042c7 元宝宝

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@qinglong.(none)')

更新/ql/repo/JDHelloWorld_jd_scripts成功...

执行结束...

**Comment by mjyhj** [comment]
解决任何更新出错问题：
docker exec -it qinglong bash -c 'cd repo/JDHelloWorld_jd_scripts && git fetch --all && git reset --hard origin/main && git pull && ql repo https://github.com/JDHelloWorld/jd_scripts "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"'

**Comment by cherrymars** [comment]
> 解决任何更新出错问题：
> docker exec -it qinglong bash -c 'cd repo/JDHelloWorld_jd_scripts && git fetch --all && git reset --hard origin/main && git pull && ql repo https://github.com/JDHelloWorld/jd_scripts "jd_|jx_|getJDCookie" "activity|backUp" "^jd[^_]|USER"'

搞定了，感谢MJ
