### ISSUE TITLE
希望能维护 docker 的任务列表

### ISSUE THREAD

**Issue by hejiadong0608** [JDHelloWorld/jd_scripts#6]
这个项目里没有原先项目的 docker 目录，虽然我可以用老项目的 docker 镜像拉取到这边的脚本，但以后有任务更新会没有办法自动更新 crontab 任务，建议维护 crontab 列表。

**Comment by Dellear** [comment]
是的，使用v4出现了类似的问题，没有检测到定时任务，直接把原有的任务全部删除了

**Comment by Dullxxs** [comment]
+1

**Comment by liwenjie119** [comment]
+1

**Comment by babyhux** [comment]
+1

**Comment by 501658362** [comment]
+1 麻烦大佬了

**Comment by chauncy** [comment]
@501658362 这个群没个通知频道很容易漏掉重要消息呀

**Comment by mjyhj** [comment]
大佬不用v4的，你们倒是可以自行维护，PR上来

**Comment by JDHelloWorld** [comment]
自己准备
