### ISSUE TITLE
关于merge错误

### ISSUE THREAD

**Issue by uminoai** [JDHelloWorld/jd_scripts#70]
![image](https://user-images.githubusercontent.com/31761657/124538224-d8700480-de4d-11eb-9b81-2b66c59d703d.png)
每次拉取你的库，都会出现merge失败的错误，然后失败的脚本里面会出现很多<<<<<<=====HEAD=====>>>>>>的代码，导致脚本执行报错。请问这个怎么解决啊

**Comment by JDHelloWorld** [comment]
仓库目录node jd_update
