### ISSUE TITLE
jd validate worker报错

### ISSUE THREAD

**Issue by Louis7904** [JDHelloWorld/jd_scripts#79]
(node:6781) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
青龙运行显示这个错误

**Comment by JDHelloWorld** [comment]
环境/网络问题，脚本没有错误
