### ISSUE TITLE
请教更新脚本后的几个问题

### ISSUE THREAD

**Issue by tony-aptx4869** [JDHelloWorld/jd_scripts#80]
请教一下，更新脚本后的几个问题。
1. 我git pull更新了脚本，发现TG机器人发送/spnode指令不返回脚本列表了。
![](http://img.tonychang1069.top/picgo/20210711010621.PNG)
2. docker容器若是关闭后开启，或者直接重启，则失败，日志显示 找不到文件  /scripts/docker/default_task.sh 我才发现更新前docker目录下一大堆文件，更新后就剩仨了。

**Comment by Clackz** [comment]
这个仓库不包含docker脚本部分

**Comment by JDHelloWorld** [comment]
仓库没有docker文件夹，环境问题自己研究
