### ISSUE TITLE
运行jd_cfd.ts后报错

### ISSUE THREAD

**Issue by djc-Sherlock** [JDHelloWorld/jd_scripts#84]
![image](https://user-images.githubusercontent.com/51894967/125378979-483c3d00-e3c2-11eb-9340-f73923d5b8ce.png)
`
Error: getaddrinfo EAI_AGAIN api.sharecode.ga
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.sharecode.ga',
  config: {
    url: 'https://api.sharecode.ga/api/jxcfd/insert?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/api/jxcfd/insert?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'api.sharecode.ga',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/jxcfd/insert',
      search: '?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/jxcfd/insert?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: api.sharecode.ga\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/jxcfd/insert?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.sharecode.ga',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://api.sharecode.ga/api/jxcfd/insert?code=397ACBBC9872E851376A162B85B90C3FD4E178035363183B00B1996BC6A2F392&farm=65793673ccb643118e6244bee67003ce',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}`

**Comment by kongren978** [comment]
+1

**Comment by qqiuqingx** [comment]
问个小白问题，怎么拉去的ts脚本啊 我拉去的全是js的

**Comment by djc-Sherlock** [comment]
如果是青龙的，config.sh有配置项，添加.ts的后缀名




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JDHelloWorld/jd_scripts] 运行jd_cfd.ts后报错 (#84)





 
问个小白问题，怎么拉去的ts脚本啊 我拉去的全是js的
 
&mdash;

**Comment by qirenzhidao** [comment]
> 
> 
> 问个小白问题，怎么拉去的ts脚本啊 我拉去的全是js的

用的青龙吧，青龙默认只拉后缀py js。你去配置文件里修改

**Comment by JDHelloWorld** [comment]
自己dns问题访问不了助力池

**Comment by djc-Sherlock** [comment]
我是放在阿里云服务器上的，是服务器的问题吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 中午11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JDHelloWorld/jd_scripts] 运行jd_cfd.ts后报错 (#84)





 
自己dns问题访问不了助力池
 
&mdash;

**Comment by msccreater** [comment]
ts文件,你们怎么运行的?用的node跑的,识别不了
