### ISSUE TITLE
node本地跑的,ts文件怎么运行?

### ISSUE THREAD

**Issue by msccreater** [JDHelloWorld/jd_scripts#85]
node本地跑的,ts文件怎么运行?

**Comment by Clackz** [comment]
安装typescript和ts-node后用tsc转译或者直接ts-node运行

**Comment by taichao1** [comment]
请问你们服务器用的什么DNS才可以访问互助池，我之前改8.8.8.8可以，今天发现不行了，改114也不行。。你们改的什么啊？？

**Comment by loveme1573** [comment]
sudo npm i -g typescript ts-node
tsc *ts   tsc转译之后 node name.js运行或者
ts-node name.ts 直接运行

**Comment by JDHelloWorld** [comment]
npm i -g @types/node tslib typescript ts-node
ts-node xx.ts
