### ISSUE TITLE
京喜牧场多账号运行其中有黑号则运行中断

### ISSUE THREAD

**Issue by xpflying** [JDHelloWorld/jd_scripts#87]
多账号运行jd_jxmc，中间一个号是黑号没有开通过京喜牧场，脚本执行到这个账号时会报错退出
(node:1281) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at /ql/scripts/jd_scripts/jd_jxmc.js:80:54
    at step (/ql/scripts/jd_scripts/jd_jxmc.js:39:23)
    at Object.next (/ql/scripts/jd_scripts/jd_jxmc.js:20:53)
    at fulfilled (/ql/scripts/jd_scripts/jd_jxmc.js:11:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:1281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JDHelloWorld** [comment]
下个版本修复

**Comment by xpflying** [comment]
大佬，这个问题有出现了，也是执行到黑号报错

`(node:43) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'lastgettime' of undefined
    at /scripts/helloworld/jd_jxmc.js:93:53
    at step (/scripts/helloworld/jd_jxmc.js:39:23)
    at Object.next (/scripts/helloworld/jd_jxmc.js:20:53)
    at fulfilled (/scripts/helloworld/jd_jxmc.js:11:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:43) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
