### ISSUE TITLE
报告一些已经失效的脚本和活动

### ISSUE THREAD

**Issue by DarkAge2018** [JDHelloWorld/jd_scripts#88]
天天加速 jd_speed.js 
活动已经在4月份下线

京喜农场 jd_jxnc.js 
目前只剩一个种子而且显示已经领完，实际上无法领取新种子
并且该活动界面会导流至京喜牧场，应该是凉了

疯狂的joy jd_crazy_joy.js jd_crazy_joy_bonus.js  jd_crazy_joy_coin.js
三个脚本已经失效，活动入口也找不到了

东东小窝 jd_small_home.js
运行日志提示“找不到api”

明星小店 jd_star_shop.js
运行日志提示“获取活动失败”

超级直播间红包雨 jd_live_redrain.js
还是6月份的直播间信息

**Comment by JDHelloWorld** [comment]
谢谢，已删。

**Comment by 124754649** [comment]
删除脚本了吧？jd_blueCoin.js 东东超市兑换奖品没了？

**Comment by mjyhj** [comment]
不要乱说，天天加速 jd_speed.js 是正常的，只是概率很低
早1，2个星期我都抽中了

crazy_joy接口一直也正常，只是进去打不开，现在也解开了，能正常进去，也能合成
不过没有用而已

**Comment by DarkAge2018** [comment]
> 不要乱说，天天加速 jd_speed.js 是正常的，只是概率很低
> 早1，2个星期我都抽中了
> 
> crazy_joy接口一直也正常，只是进去打不开，现在也解开了，能正常进去，也能合成
> 不过没有用而已

下线公告是官方发的，脚本里面有链接，自己进去看，现在的页面什么都没有
你有京豆是因为你买某个种类的商品完成了以前领取的任务

**Comment by 2Dou** [comment]
疯狂的joy 活动还在，但是脚本好像不行了，能修复一下吗？

**Comment by ilaotan** [comment]
> 疯狂的joy 活动还在，但是脚本好像不行了，能修复一下吗？

群友都在喷,都没豆子了还修个锤子

**Comment by hyzaw** [comment]
@ilaotan 修nm修 没豆子

**Comment by hyzaw** [comment]
@hyzaw 🙈
