### ISSUE TITLE
点点券二代  领取点点券失败

### ISSUE THREAD

**Issue by 1273457900** [JDHelloWorld/jd_scripts#89]
可以自动做任务，但是收取点点券时候失败

开始【京东账号1】没有青柠

bubble: 60 1700953883
ZooFakerNecklace: 385.299ms
Bubble Error:  { rtn_code: 403, rtn_msg: '非法请求！' }
bubble: 20 1701003613
Bubble Error:  { rtn_code: 403, rtn_msg: '非法请求！' }
bubble: 20 1701130174
Bubble Error:  { rtn_code: 403, rtn_msg: '非法请求！' }
bubble: 20 1701031505
Bubble Error:  { rtn_code: 403, rtn_msg: '非法请求！' }
bubble: 20 1700962783
Bubble Error:  { rtn_code: 403, rtn_msg: '非法请求！' }

此账号是中文用户名，其他账号运行正常

**Comment by JDHelloWorld** [comment]
可以重新运行试试

**Comment by 1273457900** [comment]
> 可以重新运行试试

重新运行 一直是这个错误， 
只有中文用户名的账号出现了 这个错误 
在领取点点券时候

任务可以正常领取，也可以正常做任务，

bug出现在收取 点点券时候

**Comment by JDHelloWorld** [comment]
没有bug
