### ISSUE TITLE
jd_bean_sign.js下载JD_DailyBonus时提示Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hch0086** [JDHelloWorld/jd_scripts#93]
检测到您当前网络环境不能访问外网,将使用jsdelivr CDN下载JD_DailyBonus.js文件
JD_DailyBonus.js文件  CDN刷新成功
JD_DailyBonus.js 文件下载异常:TypeError: Cannot convert undefined or null to object

JD_DailyBonus.js 文件不存在，停止执行京东多合一签到

**Comment by Clackz** [comment]
网络问题，自行解决
