### ISSUE TITLE
无法运用ts脚本如cfd等

### ISSUE THREAD

**Issue by walle-test** [JDHelloWorld/jd_scripts#94]
![image](https://user-images.githubusercontent.com/75666036/125904051-60e39945-2598-4a74-a14a-3c20a1712319.png)
手动执行提示找不到ts-node
/usr/local/bin/jd: line 357: ts-node: command not found

**Comment by JDHelloWorld** [comment]
依赖没装对，环境问题自行解决，非脚本问题
