### ISSUE TITLE
TypeError: TS_USER_AGENTS_1.requireConfig is not a function

### ISSUE THREAD

**Issue by ilee593** [JDHelloWorld/jd_scripts#97]
root@jd:/jd $ ts-node /jd/scripts/jd_cfd.ts
帮助HelloWorld: true
帮助助力池: true
token: tk01wc65f1cd3a8neS9HdmlBelh1V8QuhnQfOFUGB5UTEolqQjmJh4vJy03zeec4pN6ZTvffPt90WDjGcPyd0kcOx4vN
(node:13781) UnhandledPromiseRejectionWarning: TypeError: TS_USER_AGENTS_1.requireConfig is not a function
    at /jd/scripts/jd_cfd.ts:65:31
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13781) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by singyueyang** [comment]
同样错误，求解决。

**Comment by Michaol** [comment]
rm -rf /ql/scripts/TS*.js
